name: Build & Publish Jupyter Pytorch Full Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-pytorch-full/**
      - components/example-notebook-servers/jupyter-pytorch/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  DOCKER_USER: kubeflownotebookswg
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build and push Notebook Server images
      run: |
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-pytorch-full
        make docker-build-cuda -C jupyter-pytorch-full
        make docker-push-cpu -C jupyter-pytorch-full
        make docker-push-cuda -C jupyter-pytorch-full

    - name: Build and push latest Notebook Server images
      if: github.ref == 'refs/heads/master'
      run: |
        export TAG=latest
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-pytorch-full
        make docker-build-cuda -C jupyter-pytorch-full
        make docker-push-cpu -C jupyter-pytorch-full
        make docker-push-cuda -C jupyter-pytorch-full 

    - name: Build and push Notebook Server images on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-pytorch-full
        make docker-build-cuda -C jupyter-pytorch-full
        make docker-push-cpu -C jupyter-pytorch-full
        make docker-push-cuda -C jupyter-pytorch-full
