name: VWA Intergration Test
on:
  pull_request:
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
    branches:
      - master
      - v*-branch

env:
  IMG: volumes-web-app
  TAG: intergration-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build VWA Image 
      run: |
        cd components/crud-web-apps/volumes
        make docker-build 

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Load Image into KinD Cluster 
      run: |
        kind load docker-image ${{env.IMG}}:${{env.TAG}}

    - name: Install kustomize
      run: ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./components/testing/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd components/crud-web-apps/volumes/manifests
        kubectl create ns kubeflow

        export CURRENT_VWA_IMG=docker.io/kubeflownotebookswg/volumes-web-app:latest
        export PR_VWA_IMG=${{env.IMG}}:${{env.TAG}}

        kustomize build overlays/istio | sed "s#$CURRENT_VWA_IMG#$PR_VWA_IMG#g" |  kubectl apply -f -
        kubectl wait pods -n kubeflow -l app=volumes-web-app --for=condition=Ready --timeout=300s
